# Required items.
game: "Watch_Dogs 2"
api: 1
steamID: 447040
uid: com.thegreatcabbage.watch_dogs2
author: TheGreatCabbage
packageName: watch_dogs2
features:
  - graphics 

# Optional items.
graphicsConfig: $!DOCUMENTS!$/My Games/Watch_Dogs 2/WD2_GamerProfile.xml
gameDirectory: "WATCH_DOGS2"
verificationPaths:
  - bin/WatchDogs2.exe